"""Initial Migration

Revision ID: bdee3533711f
Revises: 
Create Date: 2026-10-02 21:13:46.741793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdee3533711f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conteudos',
    sa.Column('cont_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cont_nome', sa.String(length=30), nullable=False),
    sa.Column('cont_etapa', sa.Enum('1', '2', '3', 'ENEM', name='etapa_enum'), nullable=False),
    sa.Column('cont_slide_pdf', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cont_id')
    )
    op.create_table('usuarios',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_nome', sa.String(length=80), nullable=False),
    sa.Column('user_matricula', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_ano_letivo', sa.Integer(), nullable=True),
    sa.Column('user_curso', sa.String(length=30), nullable=True),
    sa.Column('user_data_nascimento', sa.Date(), nullable=True),
    sa.Column('user_foto_url', sa.String(length=100), nullable=True),
    sa.Column('user_progresso', sa.JSON(), nullable=False),
    sa.Column('user_media_matematica', sa.Double(), nullable=True),
    sa.CheckConstraint('user_ano_letivo BETWEEN 1 AND 4', name='ck_user_ano_letivo'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_matricula')
    )
    op.create_table('acessos',
    sa.Column('ace_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ace_user_id', sa.Integer(), nullable=False),
    sa.Column('ace_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('ace_hora_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ace_user_id'], ['usuarios.user_id'], ),
    sa.PrimaryKeyConstraint('ace_id')
    )
    op.create_table('questoes',
    sa.Column('ques_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ques_cont_id', sa.Integer(), nullable=False),
    sa.Column('ques_enunciado', sa.Text(), nullable=False),
    sa.Column('ques_alternativas', sa.JSON(), nullable=False),
    sa.Column('ques_etapa', sa.Enum('1', '2', '3', 'ENEM', name='etapa_enum'), nullable=False),
    sa.Column('ques_nivel_dificuldade', sa.Enum('Fácil', 'Médio', 'Difícil', name='nivel_dificuldade_enum'), nullable=False),
    sa.Column('ques_resposta_correta', sa.Enum('A', 'B', 'C', 'D', 'E', name='alternativa_enum'), nullable=False),
    sa.ForeignKeyConstraint(['ques_cont_id'], ['conteudos.cont_id'], ),
    sa.PrimaryKeyConstraint('ques_id')
    )
    op.create_table('usuario_conteudos',
    sa.Column('usercont_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usercont_user_id', sa.Integer(), nullable=False),
    sa.Column('usercont_cont_id', sa.Integer(), nullable=False),
    sa.Column('usercont_concluido', sa.Boolean(), nullable=False),
    sa.Column('usercont_ultimo_acesso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usercont_cont_id'], ['conteudos.cont_id'], ),
    sa.ForeignKeyConstraint(['usercont_user_id'], ['usuarios.user_id'], ),
    sa.PrimaryKeyConstraint('usercont_id'),
    sa.UniqueConstraint('usercont_user_id', 'usercont_cont_id', name='uq_user_conteudo')
    )
    op.create_table('resposta_questoes',
    sa.Column('respques_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('respques_user_id', sa.Integer(), nullable=False),
    sa.Column('respques_ques_id', sa.Integer(), nullable=False),
    sa.Column('respques_alternativa_escolhida', sa.Enum('A', 'B', 'C', 'D', 'E', name='alternativa_enum'), nullable=False),
    sa.Column('respques_acertou', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['respques_ques_id'], ['questoes.ques_id'], ),
    sa.ForeignKeyConstraint(['respques_user_id'], ['usuarios.user_id'], ),
    sa.PrimaryKeyConstraint('respques_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta_questoes')
    op.drop_table('usuario_conteudos')
    op.drop_table('questoes')
    op.drop_table('acessos')
    op.drop_table('usuarios')
    op.drop_table('conteudos')
    # ### end Alembic commands ###
