"""Initial Migration

Revision ID: febd31bab4b0
Revises: 
Create Date: 2026-09-15 10:19:22.201376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febd31bab4b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conteudos',
    sa.Column('cont_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cont_nome', sa.String(), nullable=True),
    sa.Column('cont_etapa', sa.String(), nullable=True),
    sa.Column('cont_slide_pdf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cont_id')
    )
    op.create_table('usuarios',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_nome', sa.String(), nullable=True),
    sa.Column('user_matricula', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_ano_letivo', sa.String(), nullable=True),
    sa.Column('user_curso', sa.String(), nullable=True),
    sa.Column('user_data_nascimento', sa.Date(), nullable=True),
    sa.Column('user_foto_url', sa.String(), nullable=True),
    sa.Column('user_ofensiva_dias', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_matricula')
    )
    op.create_table('acessos',
    sa.Column('ace_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ace_user_id', sa.Integer(), nullable=True),
    sa.Column('ace_data', sa.Date(), nullable=True),
    sa.Column('ace_hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('ace_hora_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ace_user_id'], ['usuarios.user_id'], ),
    sa.PrimaryKeyConstraint('ace_id')
    )
    op.create_table('questoes',
    sa.Column('ques_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ques_enunciado', sa.Text(), nullable=True),
    sa.Column('ques_alternativas', sa.JSON(), nullable=True),
    sa.Column('ques_etapa', sa.String(), nullable=True),
    sa.Column('ques_nivel_dificuldade', sa.String(), nullable=True),
    sa.Column('ques_cont_id', sa.Integer(), nullable=True),
    sa.Column('ques_resposta_correta', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ques_cont_id'], ['conteudos.cont_id'], ),
    sa.PrimaryKeyConstraint('ques_id')
    )
    op.create_table('usuario_conteudos',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usercont_user_id', sa.Integer(), nullable=True),
    sa.Column('usercont_cont_id', sa.Integer(), nullable=True),
    sa.Column('usercont_concluido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usercont_cont_id'], ['conteudos.cont_id'], ),
    sa.ForeignKeyConstraint(['usercont_user_id'], ['usuarios.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('resposta_questoes',
    sa.Column('respques_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('respques_user_id', sa.Integer(), nullable=True),
    sa.Column('respques_ques_id', sa.Integer(), nullable=True),
    sa.Column('respques_alternativa_escolhida', sa.String(), nullable=True),
    sa.Column('respques_acertou', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['respques_ques_id'], ['questoes.ques_id'], ),
    sa.ForeignKeyConstraint(['respques_user_id'], ['usuarios.user_id'], ),
    sa.PrimaryKeyConstraint('respques_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta_questoes')
    op.drop_table('usuario_conteudos')
    op.drop_table('questoes')
    op.drop_table('acessos')
    op.drop_table('usuarios')
    op.drop_table('conteudos')
    # ### end Alembic commands ###
